### ISSUE TITLE
Select MFCC library with python bindings

### ISSUE THREAD

**Issue by MainRo** [MainRo/deep-speaker#1]
An MFCC library is needed to extract features. It should be implemented in rust, with python bindings via cbindgen and cffi. some crates are availabe:

- https://crates.io/crates/vox_box
- https://crates.io/crates/mel

we must test them to see if they can provide the same result than the default tensorflow one, and allow for more configuration.

Otherwise a new library can be written, preferably on top of an existing dct library. One is available here:

- https://crates.io/crates/rustdct

If no serious option exists, then fftw can be used as a base of a new mfcc rust library:

- http://fftw.org/

**Comment by aouinizied** [comment]
Another option is to use Speechpy: https://github.com/astorfi/speechpy0
